services:
  - type: web
    name: demandwise-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
    branch: main
    rootDir: backend

  - type: static
    name: demandwise-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    branch: main
    rootDir: frontend
